#!/bin/bash
	app=dyndns
	
# The parameter $1 is the backup directory location which will be compressed afterward
	backup_dir=$1/apps/$app
	sudo mkdir -p $backup_dir
	sudo cp -a /etc/ddclient.conf $backup_dir/ddclient.conf